### ISSUE TITLE
Cross-platform test failures unmasked by CI install fix: 29 on Windows, 2 on macOS

### ISSUE THREAD

**Issue by hanzlahabib** [hanzlahabib/rcode#889]
## Context

PR #888 (fixes #887) added the missing `pnpm install` to the test matrix. That unmasked latent cross-platform failures — the suite had never actually executed on macOS/Windows before (it crashed at module load with `Cannot find module 'zod'`), so these are pre-existing bugs, not regressions from #888.

Run: https://github.com/hanzlahabib/rcode/actions/runs/27432528373

## macOS (2 failures)
- `safeRmSync removes a regular directory inside the project root`
- `safeRmSync allows nested paths inside the root`
- Likely the classic `/tmp` → `/private/tmp` realpath mismatch (same family as the TMPDIR pin in 5d78a4b).

## Windows (29 failures, e.g.)
- `--purge removes .rcode/ and .planning/...` — `ENOENT ... Temp\rcode-test-*\.planning\PROJECT.md` (path handling)
- `--purge with .planning symlinked outside the project root refuses to traverse (#688)` — symlinks need elevation on Windows runners
- `router injects the matching command body + args` — regex mismatch (likely CRLF)
- `codex install copies bodies + router and merges the hook` / `antigravity install merges a UserPrompt hook` — hook merge assertions

## Suggested approach
- Triage into: path-separator bugs, TMPDIR/realpath, symlink-dependent tests (skip-on-windows where the feature itself is posix-only), CRLF-sensitive regexes
- Ubuntu remains the gating signal meanwhile; mac/win can be made non-blocking (`continue-on-error`) until fixed if desired
